create table repo
(
    id                 int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            int    not null,
    repo_id            bigint not null,
    repo_name          text   not null,
    github_link        text   not null,
    github_description text,
    star_count         int   not null,
    owner_avatar_url   text,
    tags               text[]
);

ALTER TABLE repo
    ADD CONSTRAINT user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) MATCH FULL;
